### ISSUE TITLE
Upgrade to Spring Boot 2.7.2

### ISSUE THREAD

**Issue by klopfdreh** [micrometer-metrics/prometheus-rsocket-proxy#55]
Because we require prometheus rsocket proxy server to be updated to the newest Spring Boot Version 2.7.0 due to the implementation of generating the key store based on certificates: https://github.com/spring-projects/spring-boot/commit/d387b3fa81b36f2bcc4fe0da9f3e60eceec59f22 - I wanted to ask if there is a chance to see a 1.5.x version with this, soon?

**Comment by shakuzen** [comment]
> I wanted to ask if there is a chance to see a 1.5.x version with this, soon?

Yes, we should be able to do that. I've committed the changes for upgrading to Spring Boot 2.7.2. Would you please try out snapshots before we do a release?

**Comment by klopfdreh** [comment]
> > I wanted to ask if there is a chance to see a 1.5.x version with this, soon?
> 
> Yes, we should be able to do that. I've committed the changes for upgrading to Spring Boot 2.7.2. Would you please try out snapshots before we do a release?

I tested it locally, but only for http (not https):
- First I checked out this git repository
- Then I started `PrometheusRocketProxyMain` in the `proxy` submodule
- After this I created an example project with the following settings

application.yml:
```yaml
server:
  port: 8090
management:
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        rsocket:
          host: localhost
          port: 7001
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
```
pom.xml (I used maven and yes I use Apple Silicon 😀):
```xml
        <dependency>
            <groupId>io.micrometer.prometheus</groupId>
            <artifactId>prometheus-rsocket-spring</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer.prometheus</groupId>
            <artifactId>prometheus-rsocket-client</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-resolver-dns-native-macos</artifactId>
            <version>4.1.73.Final</version>
            <classifier>osx-aarch_64</classifier>
        </dependency>
```
- Then I called `http://localhost:8080/metrics/connected` and the metrics of the test application were present
Example:
`application_ready_time_seconds{main_application_class="prometheus.rsocket.proxy.test.TestApplication",} 1.045`

I hope that is enough to ensure the proxy to run without any issues.
